dist: bionic
language: ruby
rvm: 2.7
before_script: bundle exec rake compile
script: bundle exec rake test
cache: bundler
addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
notifications:
  email:
    on_success: never
    on_failure: change
